config/routes.rb
Rails.application.routes.draw do

  root 'lists#index'

  resources :lists
  resources :tasks

  resources :lists do
    resources :tasks
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    validates :title, presence: true, length: { maximum: 50 }
    has_many :tasks, dependent: :destroy
end
    

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :list_id, presence: true
  validates :title, presence: true, length: { maximum: 150 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @listall = List.all
  end

  def new
    @list = List.new
  end


  #  List Show
  def show
    @list = List.find(params[:id])
    @task = @list.tasks.new
    @todo = @list.tasks.where(completed: false).order(id: :desc)
    @completed_tasks = @list.tasks.where(completed: true).order(id: :desc)
  end


  # Destroy list
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to request.referrer || root_url
    flash[:success] = "List (#{@list.title}) deleted successfully"

  end


  # Create list
  def create
    @list = List.create(list_param)
    if @list.save
      flash[:success] = "List (#{@list.title}) created successfully"
      redirect_to root_path
    else
      render 'new'
    end

  end

  private

  def list_param
    params.require(:list).permit(:title)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_list, only: [:create, :update, :destroy]

  def new
    @task = Task.new(list_id: params[:list_id])
  end


  # Create Task
  def create
    @task = @list.tasks.create(task_param)
    @task.completed = false
    @task.save

    @todo = @list.tasks.where(completed: false).order(id: :desc)
    @completed_tasks = @list.tasks.where(completed: true).order(id: :desc)

    respond_to do |format|
      format.html {redirect_to request.referrer || root_url}
      format.js
    end

  end


  # Remove task
  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy

    @todo = @list.tasks.where(completed: false).order(id: :desc)
    @completed_tasks = @list.tasks.where(completed: true).order(id: :desc)

    respond_to do |format|
      format.html {redirect_to request.referrer || root_url}
      format.js
    end
  end


  def update

    @task = Task.find(params[:id])
    if @task.completed
      @task.update(completed: false)
    else
      @task.update(completed: true)
    end

    @todo = @list.tasks.where(completed: false).order(id: :desc)
    @completed_tasks = @list.tasks.where(completed: true).order(id: :desc)

    respond_to do |format|
      format.html {redirect_to request.referrer || root_url}
      format.js
    end
  end


  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def task_param
    params.require(:task).permit(:title)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<div class="footer text-center">
    <span>Copyright © 2018 <a href="https://eviathos.pl">Eviathos.pl - Jacek Kowalski</a> - All rights reserved.</span>
</div>

app/views/layouts/_header.html.erb
<div class="jumbotron text-center">
    <h1>TODO APP</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    
<div class="content page-wrapper">
    <%= yield %>
</div>

<%= render "layouts/footer" %>

  </body>
</html>

app/views/lists/_list.html.erb
<div id="todo-list" class="container col-md-8 todo-list">


  <div class="row list-header">


    <div class="list-box list-name">
      <%= list.title %>
    </div>

    <div class="list-box list-buttons ">

      <%= link_to list, {data: {turbolinks: false}, class: "btn btn1 btn-outline-warning"} do %>
        <%= icon('fas', 'sign-in-alt') %>
      <% end %>

      <%= link_to list, :class => "btn btn2 btn-outline-warning", method: :delete,
                  data: {confirm: "Are you sure? All tasks will be removed."} do %>
        <%= icon('far', 'trash-alt') %>
      <% end %>


    </div>

  </div>

  <div class="row list-footer">


    <div class="list--footer-box col-md-6">
      <% if list.tasks.length == 0 %>
        <span>You have not added any tasks!</span>
      <% else %>
        <span>You have</span> <span class="badge badge-light"> <%= pluralize(list.tasks.length, 'task') %></span>
        <span>on this list.</span>
      <% end %>
    </div>


    <div class="list--footer-box-date col-md-6">
      <span class="badge badge-light"><%= l list.created_at, format: :long %></span> |
      <span class="badge badge-light">Created <%= time_ago_in_words(list.created_at) %> ago.</span>
    </div>


  </div>


</div>

app/views/lists/index.html.erb
<div class=" todo-intro">


  <div class="list-holder">

    <% if @listall.any? %>

      <div class="form-button center-text">
        <%= link_to("Create New TODO", new_list_path, :class => "btn btn-outline-warning") %>
      </div>

      <% @listall.each do |list| %>
        <%= render "list", list: list %>
      <% end %>

    <% else %>

      <h2>Let's start by creating a new todo list!</h2>

      <div class="form-button center-text">
        <%= link_to("Create New TODO", new_list_path, :class => "btn btn-outline-warning") %>
      </div>

    <% end %>


  </div>
</div>

app/views/lists/new.html.erb
<div class="container">

  <div class="col-md-6 mx-auto">


    <%= form_for @list, url: lists_path do |f| %>

      <%= render 'shared/error_messages', object: @list %>
      <%= f.text_field :title, :id => "item", :placeholder => "List Title", :class => "form-control" %>
      <div class="form-button text-center">
        <%= button_tag(:id => "add", :class => "btn btn-outline-warning") do %>
          Create
        <% end %>
      </div>
    <% end %>
  </div>

</div>

<div class="form-button text-center">
  <%= link_to("Back", root_path, :class => "btn btn-outline-warning") %>
</div>

app/views/lists/show.html.erb
<div class="container">


  <div class="list--show-header">

    <h1><%= @list.title %>

      <% if @list.tasks.count == 0 %>
        <span id="task-count-parent" class="not-displayed badge badge-light"> <%= @list.tasks.count %></span>
      <% else %>
        <span id="task-count-parent" class="badge badge-light"> <%= @list.tasks.count %></span>
      <% end %>

    </h1>

    <div class="list--show-date">
      <h2>
        <span class="badge badge-light">
          Created at <%= l @list.created_at, format: :long %>
        </span>

        |

        <span class="badge badge-light">
          <%= time_ago_in_words(@list.created_at) %> ago
        </span>
      </h2>
    </div>

  </div>


  <%= render "tasks/new_form" %>


  <div class="container tasks-container">

    <nav>
      <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">

        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">
          <span>Todo </span>
          <% if @todo.length == 0 %>
            <span id="todo-count-parent" class="not-displayed badge badge-light"> <%= @todo.length %></span>
          <% else %>
            <span id="todo-count-parent" class="badge badge-light"> <%= @todo.length %></span>
          <% end %>
        </a>

        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">
          <span>Completed </span>
          <% if @completed_tasks.length == 0 %>
            <span id="completed-count-parent" class="not-displayed badge badge-light"> <%= @completed_tasks.length %></span>
          <% else %>
            <span id="completed-count-parent" class="badge badge-light"> <%= @completed_tasks.length %></span>
          <% end %>
        </a>

      </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">

        <ul class="todo" id="todo">
          <% @todo.each do |task| %>
            <%= render "tasks/task", task: task %>
          <% end %>
        </ul>

      </div>
      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">

        <ul class="todo" id="completed">
          <% @completed_tasks.each do |task| %>
            <%= render "tasks/task", task: task %>
          <% end %>
        </ul>

      </div>
    </div>

  </div>


  <div class="form-button text-center">
    <%= link_to("Back", root_path, :class => "btn btn-outline-warning") %>
  </div>


  <!-- END OF CONTAINER -->
</div>

 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_destroy_form.html.erb
<%= form_tag({controller: "tasks", :action => "destroy", :id => task.id, :list_id => @list.id}, method: "delete", remote: true) do %>
  <%= button_tag( :class => "remove btn btn-nobord") do %>
     <%= icon('fas', 'trash-alt') %>    
  <% end %>
<% end %>

app/views/tasks/_new_form.html.erb
<div class="container col-md-12">

  <div class="row">


    <div class="form-new-task">


      <div id="form-prep" class="form-input">
        <%= form_with(model: [@list, @list.tasks.build], remote: true) do |f| %>
          <%= f.text_field(:title, :id => "item", :placeholder => "Enter an activity..", :class => "form-control") %>
          </div>

          <div class="form-buttons">
            <%= button_tag(:id => "add", :class => "btn btn-outline-warning") do %>
              <% icon('fas', 'plus') %>
            <% end %>

          </div>
        <% end %>

        </div>



  </div>
</div>

app/views/tasks/_task.html.erb
<div id="<%= task.id %>" class="row">


  <div class="col-md-8 task-col mx-auto">

    <li>

      <div class="task-date">


        <div class="task--created-at">

<span data-toggle="tooltip" data-placement="right" data-html="true" title="<span> <%= l task.created_at, format: :long %> </span> ">
<span class='badge badge-light'>Created <%= time_ago_in_words(task.created_at) %> ago.</span>
</span>

        </div>
        

        <% if task.completed %>

          <div class="task--completed-at">

<span data-toggle="tooltip" data-placement="right" data-html="true" title="<span> <%= l task.updated_at, format: :long %> </span> ">
<span class='badge badge-light'>Completed <%= time_ago_in_words(task.updated_at) %> ago.</span>
</span>


          </div>

        <% end %>


      </div>

      <div class="task-name">
        <%= task.title %>
      </div>

      <div class="task-buttons">
        <%= render "tasks/destroy_form", task: task %>
        <%= render "tasks/update_form", task: task %>
      </div>


    </li>


  </div>
</div>

app/views/tasks/_update_form.html.erb
<%= form_tag({:model => "list", :controller => "tasks", :action => "update", :id => task.id, :list_id => @list.id}, method: "put", remote: true) do %>
  <%= button_tag(:class => "complete btn btn-nobord") do %>



<% if task.completed %>
    <%= icon('fas', 'minus-square') %>    
     <% else %>
     <%= icon('fas', 'check-square') %>    
  <% end %>



  <% end %>
<% end %>

app/views/tasks/create.js.erb
$("#item").val("");

$('#todo').prepend( $("<%= j render 'task', task: @task %>").hide().fadeIn(500) );


 $todoCount = $("#todo-count-parent"),
 $taskCount = $("#task-count-parent"),



 $taskCount.removeClass('not-displayed')
 $todoCount.removeClass('not-displayed')

 $taskCount.fadeIn()
 $todoCount.fadeIn()

 $todoCount.html('<%= @todo.length %>');
 $taskCount.html('<%= @list.tasks.count %>');
$('[data-toggle="tooltip"]').tooltip();
$('.list--show-header').find( 'span.badge' ).addClass('animation-ring').delay(1500).queue(function(){
    $(this).removeClass('animation-ring').dequeue(); 
  });

app/views/tasks/destroy.js.erb
$("#<%= @task.id %>").fadeOut(500, function() {
  $(this).remove();
});
$('.list--show-header').find( 'span.badge' ).addClass('animation-ring').delay(500).queue(function(){
    $(this).removeClass('animation-ring').dequeue(); 
  });


 $completedCount = $("#completed-count-parent"),
 $todoCount = $("#todo-count-parent"),
 $taskCount = $("#task-count-parent"),

<% if @list.tasks.length == 0 %>
$taskCount.fadeOut()
<% else %>
$taskCount.html('<%= @list.tasks.length %>');
<% end %>


<% if @todo.length == 0 %>
$todoCount.fadeOut()
<% else %>
$todoCount.html('<%= @todo.length %>');
<% end %>


<% if @completed_tasks.length == 0 %>
$completedCount.fadeOut()
<% else %>
$completedCount.html('<%= @completed_tasks.length %>');
<% end %>

app/views/tasks/update.js.erb
$("#<%= @task.id %>").slideUp( function() {
  $(this).remove();
});



$("#<%= @task.id %>").slideUp( function() {
  $(this).remove();
});



 $completedCount = $("#completed-count-parent"),
 $todoCount = $("#todo-count-parent"),
 $taskCount = $("#task-count-parent"),


<% if @completed_tasks.length == 0 %>
 $completedCount.fadeOut()
 $completedCount.fadeIn()
 $completedCount.removeClass('not-displayed')
<% end %>

<% if @todo.length == 0 %>
 $todoCount.fadeOut()
<% else %>
 $todoCount.fadeIn()
 $todoCount.removeClass('not-displayed')
<% end %>


 $taskCount.html('<%= @list.tasks.length %>');

<% if @task.completed %>
$("#completed").prepend( $(" <%= j render 'tasks/task', task: @task %>").hide().fadeIn(1100) );


 $todoCount.html('<%= @todo.length %>');
 $completedCount.html('<%= @completed_tasks.length %>');


<% else %>
$("#todo").prepend( $(" <%= j render 'tasks/task', task: @task %>").hide().fadeIn(1100) );
       

 $todoCount.html('<%= @todo.length %>');
 $completedCount.html('<%= @completed_tasks.length %>');

<% end %>


$('[data-toggle="tooltip"]').tooltip();